name: Build and Test

on:
  push:
    branches: [main]
    paths:
      [
        "Light.DatabaseAccess.EntityFrameworkCore/**",
        "Light.DatabaseAccess.EntityFrameworkCore.Tests/**",
        "Light.DatabaseAccess.EntityFrameworkCore.sln",
        "build-and-test.yml",
      ]
  pull_request:
    branches: [main]
    paths:
      [
        "Light.DatabaseAccess.EntityFrameworkCore/**",
        "Light.DatabaseAccess.EntityFrameworkCore.Tests/**",
        "Light.DatabaseAccess.EntityFrameworkCore.sln",
        "build-and-test.yml",
      ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./Light.DatabaseAccess.EntityFrameworkCore.sln
      - name: Build
        run: dotnet build ./Light.DatabaseAccess.EntityFrameworkCore.sln -c Release --no-restore
      - name: Test
        run: dotnet test ./Light.DatabaseAccess.EntityFrameworkCore.Tests/Light.DatabaseAccess.EntityFrameworkCore.Tests.csproj -c Release --no-build --verbosity normal
